In [1]:
#Consumer Price Index from Bureau of Labor Statistics
#created by John Broberg on 2022-05-22

#cd
#cd Desktop/ConsumerPriceIndex
#git pull https://github.com/JohnBroberg/ConsumerPriceIndex.git


import pandas as pd
import numpy as np
import seaborn as sns

url = 'http://www.bls.gov/news.release/cpi.t01.htm'
dfs = pd.read_html(url, header=0)

print(len(dfs))

1

In [2]:
type(dfs[0])

pandas.core.frame.DataFrame

In [3]:
df = dfs[0]
df

,Expenditure category,RelativeimportanceJul.2022,Unadjusted indexes,Unadjusted indexes.1,Unadjusted indexes.2,Unadjusted percent change,Unadjusted percent change.1,Seasonally adjusted percent change,Seasonally adjusted percent change.1,Seasonally adjusted percent change.2
0,Expenditure category,RelativeimportanceJul.2022,Aug.2021,Jul.2022,Aug.2022,Aug.2021-Aug.2022,Jul.2022-Aug.2022,May2022-Jun.2022,Jun.2022-Jul.2022,Jul.2022-Aug.2022
1,All items,100.000,273.567,296.276,296.171,8.3,0.0,1.3,0.0,0.1
2,Food,13.527,279.135,308.532,310.875,11.4,0.8,1.0,1.1,0.8
3,Food at home,8.414,259.825,292.972,295.007,13.5,0.7,1.0,1.3,0.7
4,Cereals and bakery products,1.086,288.990,332.968,336.399,16.4,1.0,2.1,1.8,1.2
5,"Meats, poultry, fish, and eggs",1.900,288.367,318.141,318.867,10.6,0.2,-0.4,0.5,0.5
6,Dairy and related products,0.798,230.145,265.638,267.461,16.2,0.7,1.7,1.7,0.3
7,Fruits and vegetables,1.407,313.672,341.839,343.221,9.4,0.4,0.7,0.5,0.5
8,Nonalcoholic beverages and beverage materials,0.964,182.277,204.944,206.693,13.4,0.9,0.8,2.3,0.5
9,Other food at home,2.259,222.863,257.295,259.976,16.7,1.0,1.8,1.8,1.1
10,Food away from home(1),5.113,309.336,331.342,334.212,8.0,0.9,0.9,0.7,0.9
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Energy,8.782,246.639,325.407,305.372,23.8,-6.2,7.5,-4.6,-5.0
13,Energy commodities,5.170,281.730,405.676,358.038,27.1,-11.7,10.4,-7.6,-10.1
14,Fuel oil(1),0.165,276.557,495.910,466.755,68.8,-5.9,-1.2,-11.0,-5.9
15,Motor fuel,4.931,278.461,399.682,351.315,26.2,-12.1,11.0,-7.6,-10.5
16,Gasoline (all types),4.824,277.448,396.952,348.593,25.6,-12.2,11.2,-7.7,-10.6
17,Energy services,3.612,223.272,262.731,267.564,19.8,1.8,3.5,0.1,2.1
18,Electricity,2.658,229.088,262.347,265.191,15.8,1.1,1.7,1.6,1.5
19,Utility (piped) gas service,0.954,202.140,258.666,268.866,33.0,3.9,8.2,-3.6,3.5
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,All items less food and energy,77.691,279.507,295.646,297.178,6.3,0.5,0.7,0.3,0.6
22,Commodities less food and energy commodities,21.168,156.581,166.746,167.637,7.1,0.5,0.8,0.2,0.5
23,Apparel,2.391,121.194,125.188,127.328,5.1,1.7,0.8,-0.1,0.2
24,New vehicles,4.024,158.652,173.618,174.598,10.1,0.6,0.7,0.6,0.8
25,Used cars and trucks,4.021,197.535,213.683,212.895,7.8,-0.4,1.6,-0.4,-0.1
26,Medical care commodities(1),1.474,375.685,390.077,391.032,4.1,0.2,0.4,0.6,0.2
27,Alcoholic beverages,0.865,264.315,274.344,275.627,4.3,0.5,0.4,0.5,0.4
28,Tobacco and smoking products(1),0.511,1254.492,1349.636,1364.765,8.8,1.1,0.6,0.3,1.1
29,Services less energy services,56.523,355.423,375.060,376.980,6.1,0.5,0.7,0.4,0.6
30,Shelter,32.247,336.284,354.935,357.264,6.2,0.7,0.6,0.5,0.7
31,Rent of primary residence,7.246,349.710,370.448,373.283,6.7,0.8,0.8,0.7,0.7
32,Owners' equivalent rent of residences(2),23.654,344.327,363.311,365.993,6.3,0.7,0.7,0.6,0.7
33,Medical care services,6.807,573.500,601.056,605.883,5.6,0.8,0.7,0.4,0.8
34,Physicians' services(1),1.802,408.490,411.846,412.828,1.1,0.2,0.1,0.3,0.2
35,Hospital services(3),2.129,365.843,377.415,380.339,4.0,0.8,0.3,0.5,0.7
36,Transportation services,5.872,325.652,363.389,362.511,11.3,-0.2,2.1,-0.5,0.5
37,Motor vehicle maintenance and repair(1),1.034,320.504,343.678,349.539,9.1,1.7,2.0,1.1,1.7
38,Motor vehicle insurance,2.407,566.183,609.585,615.559,8.7,1.0,1.9,1.3,1.3
39,Airline fares,0.673,212.882,311.205,283.911,33.4,-8.8,-1.8,-7.8,-4.6
40,Footnotes (1) Not seasonally adjusted. (2) I...,Footnotes (1) Not seasonally adjusted. (2) I...,Footnotes (1) Not seasonally adjusted. (2) I...,Footnotes (1) Not seasonally adjusted. (2) I...,Footnotes (1) Not seasonally adjusted. (2) I...,Footnotes (1) Not seasonally adjusted. (2) I...,Footnotes (1) Not seasonally adjusted. (2) I...,Footnotes (1) Not seasonally adjusted. (2) I...,Footnotes (1) Not seasonally adjusted. (2) I...,Footnotes (1) Not seasonally adjusted. (2) I...

In [4]:
df1 = df[['Expenditure category', 'Unadjusted percent change']]
header1 = df1.iloc[0,0]
header2 = df1.iloc[0,1]
df1.columns = [header1, header2]

df1 = df1.dropna() \
    .drop(index=[0,40]) \
    .astype({df1.columns[1]: 'float'}) \
    .sort_values(df1.columns[1], ascending=False) \
    .style.background_gradient(axis=0, cmap='Reds') \


print('\nConsumer Price Index for All Urban Consumers (CPI-U): \
      \nU.S. city average, by expenditure category, \
      \nin order of Unadjusted percent change')
df1

Consumer Price Index for All Urban Consumers (CPI-U):
U.S. city average, by expenditure category,
in order of Unadjusted percent change